### ISSUE TITLE
Error in 

### ISSUE THREAD

**Issue by vuhondat** [Microsoft/SQL-Server-R-Services-Samples#4]
Dear Expert,

I'd tried to test but not successfully.
My environment:
OS: WS2012 R2 latest update.
SQL: 2016 ENT GA

The error was recorded the table **runlogs**:
An external script error occurred: 
Error in unserialize(as.raw(model)) : read error
Calls: source -> withVisible -> eval -> eval -> unserialize

Error in ScaleR.  Check the output for more information.
Error in eval(expr, envir, enclos) : 
  Error in ScaleR.  Check the output for more information.
Calls: source -> withVisible -> eval -> eval -> .Call
Execution halted.

Please help me to review.

Thanks,
Vu Pham

**Comment by kganesan-ms** [comment]
Hi Vu, May I ask what script from the repository you ran to get this error? Could you provide more information about the steps you carried out that resulted in this error to help us investigate? Thanks.

**Comment by hlums** [comment]
Hi Vu, it looks like you are using the energy forecasting template since you have the **runlogs** table. There should be a message for each step. Can you post the error messages for steps 2 and 3? 
The most likely cause of this error is that you don't have the permission to run Microsoft R scripts in the database. Can you follow the instructions [here](https://msdn.microsoft.com/en-us/library/mt696069.aspx) to make sure that your account is properly set up?
We haven't get a chance to test the templates with the GA version of SQL 2016. I will try to do a test by the end of this week and give you an update.

Thanks!
Hong

**Comment by hlums** [comment]
Hi Vu,

Please search for "Windows Firewall with Advanced Security" on your server. In "Outbound Rules", a rule called "Block network access for R local user accounts in SQL Server instance MSSQLSERVER" should be enabled. Disable this rule and check the runlogs table after the next job run. This should fix it.

Best,
Hong

**Comment by BartVanDerVurst** [comment]
@hlums I have the same error as @vuhondat but the Windows settings did not fix the issue. Any idea how to proceed?

**Comment by hlums** [comment]
Hi @BartVanDerVurst,

Sorry to hear that! There should be multiple steps in the runlogs table. Can you post the error message of each step? 
What's the RAM of your server? This demo is actually a little memory consuming, more than 16GB RAM would be ideal. If you are running on a laptop, try using Windows Authentication so that it only run one job instead of four.
Also, check "Services" on your computer and make sure SQL Server Launchpad is running. If not, start it and check the demo again. 

Best,
Hong

**Comment by DieselAnalytics** [comment]
I am getting a similar error. Here is my T-SQL code:

DECLARE @tip_model varbinary(max)
DECLARE @inquery nvarchar(max) 
DECLARE @RScript nvarchar(max)

SET @tip_model = (SELECT MODEL FROM nyctaxi_models where MODEL_NAME = 'Tip Predictor');
SET @inquery = 'SELECT * FROM dbo.V_TaxiTripsToBeScored';
SET @RScript = 
			N'
				library(dplyrXdf)

				NewRides <- InputDataSet 
				mod <- unserialize(as.raw(model))

				env <- new.env()
				env$ComputeDist <- function(pickup_long, pickup_lat, dropoff_long, dropoff_lat) {
					R <- 6371 / 1.609344 #radius in mile
					delta_lat <- dropoff_lat - pickup_lat
					delta_long <- dropoff_long - pickup_long
					degrees_to_radians = pi / 180.0
					a1 <- sin(delta_lat / 2 * degrees_to_radians)
					a2 <- as.numeric(a1) ^ 2
					a3 <- cos(pickup_lat * degrees_to_radians)
					a4 <- cos(dropoff_lat * degrees_to_radians)
					a5 <- sin(delta_long / 2 * degrees_to_radians)
					a6 <- as.numeric(a5) ^ 2
					a <- a2 + a3 * a4 * a6
					c <- 2 * atan2(sqrt(a), sqrt(1 - a))
					d <- R * c
					return(d)
				}

				NewRides <-
					NewRides_Xdf %>%
					mutate(NewRides_Xdf,
						   .rxArgs =
								list(
									transforms = list(direct_distance = ComputeDist(pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude)),
									transformEnvir = env
								)
					)
					
				OutputDataSet<-
					rxPredict(
								 modelObject = mod
								,data = NewRides
								,outData = NULL
								,predVarNames = "Tipped"
								,type = "response"
								,extraVarsToWrite = c("tipped", "tip_amount", "fare_amount", "passenger_count", "trip_time_in_secs", "trip_distance", "pickup_datetime","dropoff_datetime","pickup_longitude", "pickup_latitude", "dropoff_longitude", "dropoff_latitude", "payment_type", "direct_distance")
								,writeModelVars = FALSE
								,overwrite = TRUE
					)
			'

	EXEC sp_execute_external_script @language = N'R',
									@script = @RScript,
									@input_data_1 = @inquery,
									@params = N'@model varbinary(max)',
									@model = @tip_model
	WITH RESULT SETS (
	   (
		tipped char(1), 
		tip_amount float, 
		fare_amount float, 
		passenger_count int, 
		trip_time_in_secs bigint, 
		trip_distance float, 
		pickup_datetime datetime,
		dropoff_datetime datetime,
		pickup_longitude float, 
		pickup_latitude float, 
		dropoff_longitude float, 
		dropoff_latitude float, 
		payment_type char(3), 
		direct_distance float
	   )
	)

Here is the error message:

Msg 39004, Level 16, State 20, Line 18
A 'R' script error occurred during execution of 'sp_execute_external_script' with HRESULT 0x80004004.
Msg 39019, Level 16, State 1, Line 18
An external script error occurred: 
Loading required package: dplyr

Attaching package: 'dplyr'

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union


Attaching package: 'dplyrXdf'

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

Warning: namespace 'CompatibilityAPI' is not available and has been replaced
by .GlobalEnv when processing object ''
Error in eval(expr, envir, enclos) : object 'NewRides_Xdf' not found
Calls: source -> withVisible -> eval -> eval -> %>% -> eval -> eval

Error in ScaleR.  Check the output for more information.
Error in eval(expr, envir, enclos) : 
  Error in ScaleR.  Check the output for more information.
Calls: source -> withVisible -> eval -> eval -> .Call
Execution halted

**Comment by DieselAnalytics** [comment]
Everything works fine when I tested it in R Client. I thought it would be simple to add it to SQL Server but it is much more difficult then I thought. I am running everything from my local computer. I am using SQL Server 2016 Developer as my database. I am frustrated.

**Comment by DieselAnalytics** [comment]
There was a mistake in my code above that I corrected. Here is the corrected code that was using dplyr:

				NewRides <-
					NewRides %>%
					mutate(NewRides,
						   .rxArgs =
								list(
									transforms = list(direct_distance = ComputeDist(pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude)),
									transformEnvir = env
								)
					)

I also disabled the "Block network access for R local user accounts in SQL Server instance MSSQLSERVER" rule but that did not solve the issue.

**Comment by NebileK** [comment]
I still get the same error. Please help.

**Comment by hlums** [comment]
@NebileK Sorry to hear that. Which sample you are trying to run? Can you post your exact error again as SQL R has some new releases since this issue was opened. Thanks!

**Comment by jnav** [comment]
hi guys, we got same error for the code which was operating on resultset selected from database. The issue there was that we tried to parse value (using R) which was NULL and this led to same error you describe above.

Make sure that your R code can safely process your data and try to avoid NULLS in your input result set which is then processed by R script/code

Hope this helps
